services:
  app:
    build: .
    container_name: agents_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - .:/app
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "19092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  sse_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: sse_server
    ports:
      - "9095:9095"
    env_file:
      - .env
    restart: always
  

volumes:
  pgdata:
